# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Welcome to Sengatera.com.
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Thank you for visiting our website. This site is under construction. Please check again other time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://admin.sengatera.com" # the base hostname & protocol for your site
twitter_username: TBA
github_username:  TBA

# Build settings
markdown: TBA
